export const FETCH_ANIMES_REQUEST = "FETCH_ANIMES_REQUEST";
export const FETCH_ANIMES_SUCCESS = "FETCH_ANIMES_SUCCESS";
export const FETCH_ANIMES_FAILURE = "FETCH_ANIMES_FAILURE";

export const FETCH_ANIMES_FILTER_REQUEST = "FETCH_ANIMES_FILTER_REQUEST";
export const FETCH_ANIMES_FILTER_SUCCESS = "FETCH_ANIMES_FILTER_SUCCESS";
export const FETCH_ANIMES_FILTER_FAILURE = "FETCH_ANIMES_FILTER_FAILURE";