export const FETCH_ANIMEDETAIL_REQUEST = "FETCH_ANIMEDETAIL_REQUEST";
export const FETCH_ANIMEDETAIL_SUCCESS = "FETCH_ANIMEDETAIL_SUCCESS";
export const FETCH_ANIMEDETAIL_FAILURE = "FETCH_ANIMEDETAIL_FAILURE";